/**********************************/
/* Table Name: 주문 문의 */
/**********************************/
CREATE TABLE PAYMENT_INQUIRY(
		PAYMENT_INQUIRY_NO            		NUMBER(9)		 NOT NULL		 PRIMARY KEY,
		COMMENT                       		VARCHAR2(1000)		 NOT NULL,
		DATE                          		DATE		 NOT NULL,
		ANSWER_VISIBLE                		CHAR(1)		 NOT NULL,
		ANSWER_COMMENT                		VARCHAR2(1000)		 NULL ,
		MEMBERNO                      		NUMBER(9)		 NOT NULL,
		PAYMENTNO                     		NUMBER(9)		 NULL ,
  FOREIGN KEY (MEMBERNO) REFERENCES MEMBER (MEMBERNO),
  FOREIGN KEY (PAYMENTNO) REFERENCES PAYMENT (PAYMENTNO)
);

COMMENT ON TABLE PAYMENT_INQUIRY is '주문 문의';
COMMENT ON COLUMN PAYMENT_INQUIRY.PAYMENT_INQUIRY_NO is '주문 문의 번호';
COMMENT ON COLUMN PAYMENT_INQUIRY.COMMENT is '문의 내용';
COMMENT ON COLUMN PAYMENT_INQUIRY.DATE is '문의 작성일';
COMMENT ON COLUMN PAYMENT_INQUIRY.ANSWER_VISIBLE is '답변 여부';
COMMENT ON COLUMN PAYMENT_INQUIRY.ANSWER_COMMENT is '답변 내용';
COMMENT ON COLUMN PAYMENT_INQUIRY.MEMBERNO is '멤버 번호';
COMMENT ON COLUMN PAYMENT_INQUIRY.PAYMENTNO is '주문 번호';