/**********************************/
/* Table Name: 주문상세 */
/**********************************/
CREATE TABLE PAYMENT_DETAILS(
		PAYMENT_DETAILS_NO            		VARCHAR2(255)		 NOT NULL		 PRIMARY KEY,
		PAYMOUNT                      		NUMBER(9)		 NOT NULL,
		NO                            		NUMBER(9)		 NOT NULL,
		OPTIONNO                      		NUMBER(9)		 NOT NULL,
		PAYMENTNO                     		NUMBER(9)		 NULL ,
  FOREIGN KEY (OPTIONNO) REFERENCES OPTION (OPTIONNO),
  FOREIGN KEY (PAYMENTNO) REFERENCES PAYMENT (PAYMENTNO)
);

COMMENT ON TABLE PAYMENT_DETAILS is '주문상세';
COMMENT ON COLUMN PAYMENT_DETAILS.PAYMENT_DETAILS_NO is '주문 상세번호';
COMMENT ON COLUMN PAYMENT_DETAILS.PAYMOUNT is '주문 수량';
COMMENT ON COLUMN PAYMENT_DETAILS.NO is '주문 번호';
COMMENT ON COLUMN PAYMENT_DETAILS.OPTIONNO is '옵션 번호';
COMMENT ON COLUMN PAYMENT_DETAILS.PAYMENTNO is '주문 번호';