/**********************************/
/* Table Name: 신발 문의 */
/**********************************/
CREATE TABLE SHOES_INQUIRY(
		SHOES_INQUIRY_NO              		NUMBER(9)		 NOT NULL		 PRIMARY KEY,
		IN_COMMENT                    		VARCHAR2(1000)		 NOT NULL,
		IN_DATE                       		DATE		 NOT NULL,
		ANSWER_VISIBLE                		CHAR(1)		 NOT NULL,
		ANSWER_COMMENT                		VARCHAR2(1000)		 NOT NULL,
		OPTIONNO                      		NUMBER(9)		 NULL ,
		MEMBERNO                      		NUMBER(9)		 NULL ,
  FOREIGN KEY (OPTIONNO) REFERENCES OPTION (OPTIONNO),
  FOREIGN KEY (MEMBERNO) REFERENCES MEMBER (MEMBERNO)
);

COMMENT ON TABLE SHOES_INQUIRY is '신발 문의';
COMMENT ON COLUMN SHOES_INQUIRY.SHOES_INQUIRY_NO is '신발 문의 번호';
COMMENT ON COLUMN SHOES_INQUIRY.IN_COMMENT is '문의 내용';
COMMENT ON COLUMN SHOES_INQUIRY.IN_DATE is '문의 작성일';
COMMENT ON COLUMN SHOES_INQUIRY.ANSWER_VISIBLE is '답변 여부';
COMMENT ON COLUMN SHOES_INQUIRY.ANSWER_COMMENT is '답변 내용';
COMMENT ON COLUMN SHOES_INQUIRY.OPTIONNO is '옵션 번호';
COMMENT ON COLUMN SHOES_INQUIRY.MEMBERNO is '멤버 번호';